### ISSUE TITLE
Link for the API on the modlinks.xml is unsuitable for MacOS

### ISSUE THREAD

**Issue by Lisias** [ricardosouzag/ModInstaller#93]
Hi, dude!

I'm toying with the ModInstaller, and found that for the link provided on hodlinks.xml for the API is not working too well on MacOS:

```
        <ModLink>
            <Name>Modding API</Name>
            <Files>
                <File>
                    <Name>Assembly-CSharp.dll</Name>
                    <SHA1>E880EA1B2B4B57FBD6ECA36B26746F08FF4EEF9F</SHA1>
                    <Patch>1.4.3.2</Patch>
                </File>
            </Files>
            <Link>yada yada yada</Link>
            <UnixLink>yada yada yada</UnixLink>
            <Dependencies />
        </ModLink>
```

At least my GamePad was not working on this Assembly-CSharp.dll  - I didn't did a very comprehensive test however, as playing without my M30 is out of question.

So I cloned the HollowKnight.Modding project and built it on my Mac, and the resulting DLL appears to be working fine (at least the GamePad is now working).

There's a way to add it to the project, so other MacOS users can use it too?

Cheers!

**Comment by Lisias** [comment]
Just came here to say that the ModdingAPI I compiled for my Mac is working flawless since I started to use it - without any colateral effects (at least until this moment).

And I'm able to use my M30 as before modding it.

**Comment by Lisias** [comment]
After one week of heavy testing, I can confirm that my locally compiled MacOS DLL is working flawlessly, without undesired side-effects and without losing any MacOS specific features.

The problem we have now is that the `UnixLink` element of the `modlink.xml` is being used for both Linux and MacOS, but they are pretty different - from my experience on modding Unity games, the Linux compile is near the Windows one that the MacOS: I can run compiled DLL against the Windows' Unity libraries on Linux and MacOS, but I can't run DLLs compiled against the MacOS' Unity libraries on Windows neither Linux.

(go figure it out).

In a way or another, I think we need some small adjustments on the `modlinks.xml` in order to make things work smoothly for everybody. Are you interested on a pull request with this feature?

**Comment by fifty-six** [comment]
As it is, the UnixLink and Link setup is a bit of a mess which I've been planning to fix with the next update to the game. As far as Linux v Mac goes in regards to libraries, both use the same version of InControl for input handling with the Assembly between the two being identical. Windows differs in that it has XInput used. The only real pain is that the hash is poorly setup for cross-platform as every other dll tends to be platform-independent. A PR fixing this now instead of waiting for the next release would be nice considering how long the beta has been out for without making it to stable. If you don't want to bother, I could probably fix this later this week. I went ahead and put a [release up on the actual API repo](https://github.com/HollowKnight-Modding/HollowKnight.Modding/releases/tag/1.4.3.2-60) with both versions for later. Sorry for how long it's taken to get to this, I've been busy recently.

**Comment by Lisias** [comment]
I completely understand the "bust" status, I'm on the same boat - took a month to remember this. Sorry.

I will check and remember what I toyed here, and will come back to you on the week-end.

Cheers!

**Comment by fifty-six** [comment]
Took a while, but I released a new installer (fifty-six/Scarab) and that should deal with the issue as it swaps to a new version of modlinks.xml.

**Comment by Lisias** [comment]
Thank you!

I had a disk crash (induced by Apple, that screwed up the GUID partitions of two HDs of mine - the one that was failing, and the one that was its backup!!!), and still didn't had the time to rebuild my HollowKnight setup.

But I will soon - already missing playing while listening that fantastic music! :)

Cheers!
